### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by fewizz** [Kobata/animated-texture-fix#1]
NULL:

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at animfix.FastTextureAtlasSprite.checkGLError(FastTextureAtlasSprite.java:130)
    at animfix.FastTextureAtlasSprite.uploadTextureMaxMips(FastTextureAtlasSprite.java:120)
    at animfix.FastTextureAtlasSprite.func_94219_l(FastTextureAtlasSprite.java:56)
    at fastcraft.b.i.a(F:448)
    at fastcraft.Hooks.h(F:91)
    at net.minecraft.client.renderer.texture.TextureMap.func_110550_d(TextureMap.java:587)
    at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:154)
    at TextureUtils.resourcesReloaded(TextureUtils.java:277)
    at TextureUtils$1.func_110549_a(TextureUtils.java:305)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:130)
    at TextureUtils.registerResourceListener(TextureUtils.java:309)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1188)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)

and:

[14:00:18] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1250_blockSpellEffect.png, java.io.FileNotFoundException
[14:00:20] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1248_blockSpellEnhancement.png, java.io.FileNotFoundException
[14:00:20] [Client thread/ERROR]: Unable to parse metadata from genetics:textures/blocks/liquids/dna.raw.png
java.lang.RuntimeException: broken aspect ratio and not an animation
    at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:273) ~[bqd.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:229) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:124) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63) [bqf.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[14:00:22] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1253_schematicSaver.png, java.io.FileNotFoundException
[14:00:24] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1247_blockSpellParadigm.png, java.io.FileNotFoundException
[14:00:25] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1256_crystalBelljar.png, java.io.FileNotFoundException
[14:00:25] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1255_alchemicCalcinator.png, java.io.FileNotFoundException
[14:00:28] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/planks.png, java.io.FileNotFoundException
[14:00:28] [Client thread/ERROR]: Unable to parse metadata from ic2:textures/blocks/fluids/biogas_still.png
java.lang.RuntimeException: broken aspect ratio and not an animation
    at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:273) ~[bqd.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:229) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:124) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63) [bqf.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[14:00:28] [Client thread/ERROR]: Using missing texture, unable to load extrautils:textures/blocks/enderQuarryUpgrade.png, java.io.FileNotFoundException
[14:00:32] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1249_blockSpellModifier.png, java.io.FileNotFoundException
[14:00:33] [Client thread/ERROR]: Using missing texture, unable to load gravisuite:textures/blocks/block_side.png.png, java.io.FileNotFoundException
[14:00:33] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_830_bookshelf.png, java.io.FileNotFoundException
[14:00:34] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_1259_blockMimic.png, java.io.FileNotFoundException
[OptiFine] Texture size: textures/blocks, 4096x4096
[14:00:34] [Client thread/INFO]: Created: 4096x4096 textures/blocks-atlas
[OptiFine] Loading texture map: textures/items
[14:00:39] [Client thread/ERROR]: Using missing texture, unable to load missing_icon_item_5602_extrautils:textures/items/lawSword.png, java.io.FileNotFoundException
[14:00:39] [Client thread/ERROR]: Using missing texture, unable to load alchemicalwizardry:textures/items/guide.png, java.io.FileNotFoundException
[14:00:40] [Client thread/ERROR]: Using missing texture, unable to load extrabees:textures/items/misc/blutoniumDust.png, java.io.FileNotFoundException
[14:00:42] [Client thread/ERROR]: Using missing texture, unable to load alchemicalwizardry:textures/items/SigilOfTheFastMiner.png, java.io.FileNotFoundException

**Comment by Kobata** [comment]
Not compatibile with fastcraft.

**Comment by fewizz** [comment]
ohh. thanks. =]
